version: 2.1
resource_types:
  # Set status of build in github for master
  - name: github-status
    type: docker-image
    source:
      repository: dpb587/github-status-resource
      tag: master

resources:
  - name: code
    type: git
    source:
      uri: https://github.com/luispabon/php-console-logger.git
      branch: master

  - name: master-status
    type: github-status
    source:
      repository: luispabon/php-console-logger
      branch: master
      access_token: {{github-access-token}}

jobs:
  - name: analyze-master
    public: true
    plan:
      - get: code
        trigger: true

      - put: notify-master-being-built
        resource: master-status
        params: { state: "pending", commit: "code" }

      - task: tests_php_72
        file: code/concourse/task-run-tests-72.yaml

      - task: tests_php_73
        file: code/concourse/task-run-tests-73.yaml

      - task: tests_php_74
        file: code/concourse/task-run-tests-74.yaml

      - task: tests_php_80
        file: code/concourse/task-run-tests.yaml

        on_failure:
          put: master-status
          params: { state: "failure", commit: "code" }

      - put: notify-build-success
        resource: master-status
        params: { state: "success", commit: "code" }

      - task: code_coverage_reports
        params:
          CODECOV_TOKEN: {{codecov-token}}
        file: code/concourse/task-codecov.yaml
